# -*- coding: utf-8 -*-
"""HEATMAP.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19GZQ1-LNLmtotJGeD_JVclECklb6JRDg
"""

# !pip install folium
# !pip install pymongo
# !pip install dnspython
# !pip install spacy
# !pip install geopandas
# !pip install geopy

from pymongo import MongoClient
from pprint import pprint
client = MongoClient('mongodb+srv://SPUM:srinking69@myhealthcard-1nsmr.mongodb.net/Health?w=majority&retryWrites=true')
db=client.Health
db.command("serverStatus")



user=db.user
x=user.find({})

import spacy
nlp = spacy.load("en_core_web_sm")
loc=[]

for feild in x:
      cityandState=[]
      address=feild['Address']
      print(address)
      doc=nlp(address)
      s=""
      for X in doc.ents:
        if(X.label_=='GPE'):
          cityandState.append(X.text)
      print(cityandState)
      s = cityandState[-2] +","+cityandState[-1]
      print(s)
      loc.append(s)

import pandas as pd
import IPython
from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter
geolocator = Nominatim(user_agent="ADD2CORD")

lat=[]
long=[]
for x in loc:
  location = geolocator.geocode(x)
  lat.append(location.latitude)
  long.append(location.longitude)
  
df = pd.DataFrame(list(zip(lat, long)), columns =['LAT', 'LONG']) 
df['LAT'] = df['LAT'].astype(float)
df['LONG'] = df['LONG'].astype(float)
df

import folium
from folium import plugins
from folium.plugins import HeatMap

df['count'] = 1
heat_df = df[['LAT', 'LONG','count']]
locationArr = heat_df.as_matrix()
locationArr
map_infected = folium.Map(location=[22.2074, 71.9278],zoom_start = 7)
HeatMap(data=heat_df[['LAT', 'LONG', 'count']].groupby(['LAT', 'LONG']).sum().reset_index().values.tolist(), radius=10, max_zoom=13,gradient={.4: 'blue', .65: 'lime', 1: 'red'}).add_to(map_infected)
map_infected.save('heatmap.html')
map_infected