# -*- coding: utf-8 -*-
"""health_scrap.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s0jxfTrQVHtW-1EPTwDdWn9H2WP-0Dik
"""

#!pip3 install pymongo[srv]

import requests
from bs4 import BeautifulSoup
import pymongo
import re

NEWS_CATEGORY = "health"

mongo = pymongo.MongoClient("mongodb+srv://SPUM:srinking69@myhealthcard-1nsmr.mongodb.net/Health?w=majority&retryWrites=true")
newspaper_data = mongo.Health.News

url="https://rss.medicalnewstoday.com/featurednews.xml"
r = requests.get(url) 
soup = BeautifulSoup(r.content, 'html5lib') 
#print(soup.prettify()) 

items = soup.findAll("item")
print("--------------------SCRAPPING--------------------")
for item in items:
  title = item.find("title").text
  title=title.replace("Medical News Today: ","")
  guid = item.find("guid").text
  description = item.find("description").text
  print("Scraped ",title)
  newsInsert={
      'title':title,
      'guid':guid,
      'description':description
  }
  #print(newsInsert)
  newspaper_data.insert_one(newsInsert)

print("---------------ENDED SCRAPPING------------------")